/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'Tour De Azeroth',
    {
      type: 'category',
      label: 'Etaper',
      items: ['Easton Kingdoms', 'Northrend', 'Outlands', 'Kalimdor'],
    },
    {
      type: 'category',
      label: 'Årsopsummering',
      items: ['Turen 2023'],
    }
  ],
};

module.exports = sidebars;
